#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_vimfiler_welcome = false
    filetree_direction = "left"
    autocomplete_method = "coc"
    enabled_formater = "prettier"
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    snippet_engine = "ultisnips"
    enable_filetree_gitstatus = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
    name = "denite"

[[layers]]
    name = "tools"

[[layers]]
    name = 'git'

[[layers]]
  name = "github"

[[layers]]
    name = 'VersionControl'

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#html"
  emmet_leader_key = "<C-e>"
  emmet_filetyps = ['html']

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#php"

[[custom_plugins]]
    repo = "metakirby5/codi.vim"
    merged = false

[[custom_plugins]]
    repo = "voldikss/vim-translator"
    merged = false

[[custom_plugins]]
    repo = "alvan/vim-closetag"
    merged = false

[[custom_plugins]] # создание оглавления для файлов Markdown.
     repo = "mzlogin/vim-markdown-toc"
     merged = false

[[custom_plugins]]
     repo = "tpope/vim-fugitive" # для управления гитом
     merged = false

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0
